import React, { PropsWithChildren } from "react";
import Navigation from "./Navigation";
import { ScrollProvider } from "@/store/scrollContext";
import Head from "next/head";

const Layout = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <ScrollProvider>{children}</ScrollProvider>
    </>
  );
};
export default Layout;
